baseURL = "http://oxsynn.github.io/"
languageCode = "en-us"
title = "Gilbert Cisneros - System Administrator"
theme = "m10c"

[[menu.main]]
	identifier = "Post"
	name = "Posts"
	url = "/post/"

[[params.social]]
	name = "github"
	url = "https://github.com/oxsynn"
	
[params.style]
	darkestColor = "#d35050"
	darkColor = "#212121"
	lightColor = "#f5e3e0"
	lightestColor = "#f5f5f5"
	primaryColor = "#fff"

